In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('loan_dataset_20000.csv')
data.head()

,age,gender,marital_status,education_level,annual_income,monthly_income,employment_status,debt_to_income_ratio,credit_score,loan_amount,...,loan_term,installment,grade_subgrade,num_of_open_accounts,total_credit_limit,current_balance,delinquency_history,public_records,num_of_delinquencies,loan_paid_back
0,59,Male,Married,Master's,24240.19,2020.02,Employed,0.074,743,17173.72,...,36,581.88,B5,7,40833.47,24302.07,1,0,1,1
1,72,Female,Married,Bachelor's,20172.98,1681.08,Employed,0.219,531,22663.89,...,60,573.17,F1,5,27968.01,10803.01,1,0,3,1
2,49,Female,Single,High School,26181.80,2181.82,Employed,0.234,779,3631.36,...,60,76.32,B4,2,15502.25,4505.44,0,0,0,1
3,35,Female,Single,High School,11873.84,989.49,Employed,0.264,809,14939.23,...,36,468.07,A5,7,18157.79,5525.63,4,0,5,1
4,63,Other,Single,Other,25326.44,2110.54,Employed,0.260,663,16551.71,...,60,395.50,D5,1,17467.56,3593.91,2,0,2,1

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   age                   20000 non-null  int64
 1   gender                20000 non-null  object
 2   marital_status        20000 non-null  object
 3   education_level       20000 non-null  object
 4   annual_income         20000 non-null  float64
 5   monthly_income        20000 non-null  float64
 6   employment_status     20000 non-null  object
 7   debt_to_income_ratio  20000 non-null  float64
 8   credit_score          20000 non-null  int64
 9   loan_amount           20000 non-null  float64
 10  loan_purpose          20000 non-null  object
 11  interest_rate         20000 non-null  float64
 12  loan_term             20000 non-null  int64
 13  installment           20000 non-null  float64
 14  grade_subgrade        20000 non-null  object
 15  num_of_open_accounts  20000 non-null  int64
 16  total_credit_limit    20000 non-null  float64
 17  current_balance       20000 non-null  float64
 18  delinquency_history   20000 non-null  int64
 19  public_records        20000 non-null  int64
 20  num_of_delinquencies  20000 non-null  int64
 21  loan_paid_back        20000 non-null  int64
dtypes: float64(8), int64(8), object(6)
memory usage: 3.4+ MB

In [5]:
data = data.dropna()

In [7]:
data.shape

(20000, 22)

In [8]:
data.columns

Index(['age', 'gender', 'marital_status', 'education_level', 'annual_income',
       'monthly_income', 'employment_status', 'debt_to_income_ratio',
       'credit_score', 'loan_amount', 'loan_purpose', 'interest_rate',
       'loan_term', 'installment', 'grade_subgrade', 'num_of_open_accounts',
       'total_credit_limit', 'current_balance', 'delinquency_history',
       'public_records', 'num_of_delinquencies', 'loan_paid_back'],
      dtype='object')

In [9]:
data['loan_paid_back'].value_counts()

loan_paid_back
1    15998
0     4002
Name: count, dtype: int64

In [ ]:
##separate the features(input) from the target(output)
X = data.drop('loan_paid_back', axis=1)
y = data['loan_paid_back']

X.head()

,age,gender,marital_status,education_level,annual_income,monthly_income,employment_status,debt_to_income_ratio,credit_score,loan_amount,...,interest_rate,loan_term,installment,grade_subgrade,num_of_open_accounts,total_credit_limit,current_balance,delinquency_history,public_records,num_of_delinquencies
0,59,Male,Married,Master's,24240.19,2020.02,Employed,0.074,743,17173.72,...,13.39,36,581.88,B5,7,40833.47,24302.07,1,0,1
1,72,Female,Married,Bachelor's,20172.98,1681.08,Employed,0.219,531,22663.89,...,17.81,60,573.17,F1,5,27968.01,10803.01,1,0,3
2,49,Female,Single,High School,26181.80,2181.82,Employed,0.234,779,3631.36,...,9.53,60,76.32,B4,2,15502.25,4505.44,0,0,0
3,35,Female,Single,High School,11873.84,989.49,Employed,0.264,809,14939.23,...,7.99,36,468.07,A5,7,18157.79,5525.63,4,0,5
4,63,Other,Single,Other,25326.44,2110.54,Employed,0.260,663,16551.71,...,15.20,60,395.50,D5,1,17467.56,3593.91,2,0,2

In [15]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: loan_paid_back, dtype: int64

In [ ]:
##checking the columns that are of text type
X.select_dtypes(include='object').columns

Index(['gender', 'marital_status', 'education_level', 'employment_status',
       'loan_purpose', 'grade_subgrade'],
      dtype='object')

In [ ]:
from sklearn.preprocessing import LabelEncoder

le= LabelEncoder()
##label encoding
X['grade_subgrade'] = le.fit_transform(X['grade_subgrade'])

In [18]:
##one-hot encoding
X = pd.get_dummies(X, columns=['gender', 'marital_status', 'education_level', 'employment_status',
       'loan_purpose'])

In [19]:
X.head()

,age,annual_income,monthly_income,debt_to_income_ratio,credit_score,loan_amount,interest_rate,loan_term,installment,grade_subgrade,...,employment_status_Student,employment_status_Unemployed,loan_purpose_Business,loan_purpose_Car,loan_purpose_Debt consolidation,loan_purpose_Education,loan_purpose_Home,loan_purpose_Medical,loan_purpose_Other,loan_purpose_Vacation
0,59,24240.19,2020.02,0.074,743,17173.72,13.39,36,581.88,9,...,False,False,False,True,False,False,False,False,False,False
1,72,20172.98,1681.08,0.219,531,22663.89,17.81,60,573.17,25,...,False,False,False,False,True,False,False,False,False,False
2,49,26181.80,2181.82,0.234,779,3631.36,9.53,60,76.32,8,...,False,False,True,False,False,False,False,False,False,False
3,35,11873.84,989.49,0.264,809,14939.23,7.99,36,468.07,4,...,False,False,False,False,False,False,False,False,True,False
4,63,25326.44,2110.54,0.260,663,16551.71,15.20,60,395.50,19,...,False,False,False,True,False,False,False,False,False,False

In [20]:
X.select_dtypes(include='object').columns

Index([], dtype='object')

In [21]:
##split data 
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [23]:
##training using logistic regression
from sklearn.linear_model import LogisticRegression

##model initialization
model = LogisticRegression(max_iter=1000)

##train 
model.fit(X_train, y_train)

c:\Users\PC\miniconda3\envs\ml_env\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [24]:
##prediction
y_pred = model.predict(X_test)

In [31]:
##evaluating the performance
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Accuracy score:", accuracy_score(y_test, y_pred))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification report\n", classification_report(y_test, y_pred))

Accuracy score: 0.809
Confusion matrix:
 [[ 166  652]
 [ 112 3070]]
Classification report
               precision    recall  f1-score   support

           0       0.60      0.20      0.30       818
           1       0.82      0.96      0.89      3182

    accuracy                           0.81      4000
   macro avg       0.71      0.58      0.60      4000
weighted avg       0.78      0.81      0.77      4000

In [32]:
import pickle

##save the model
with open("loan_model.pkl", "wb") as file:
    pickle.dump(model, file)

# Save the LabelEncoder
with open("le_grade.pkl", "wb") as file:
    pickle.dump(le, file)

# Save feature columns (one-hot encoded)
import json

feature_columns = list(X.columns)
with open("feature_columns.json", "w") as f:
    json.dump(feature_columns, f)